language: node_js

node_js: "8"

os:
  - osx
  - linux
  - windows

branches:
  only:
    - master

addons:
    apt:
      packages:
        - xvfb

install:
  - npm install
  - npm run compile
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &

before_script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      export DISPLAY=:99.0;
      sh -e /etc/init.d/xvfb start;
      sleep 3;
    fi

script:
  - npm run lint
  - npm run test --silent

cache:
  directories:
    - node_modules

notifications:
  email:
    on_success: never
    on_failure: change
